id: AAA6DA732
title: Prayer to the Lion of Speech
type: translation
pechas:
- IB144AFA7
- IFAAF4AAA
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:50.312769
  last_modified_at: 2023-01-04 12:45:50.312786
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  IB144AFA7/E74C: 385B
  IFAAF4AAA/4DD8: 385B
